CREATE DATABASE AmazonDB;
USE AmazonDB;
CREATE TABLE Users(
	user_id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(150) UNIQUE NOT NULL,
	registered_date DATE NOT NULL,
	membership ENUM('Basic', 'Prime') not null DEFAULT 'Basic'
);    
select * from Users
create table Products(
	product_id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(200) NOT NULL,
	price DECIMAL(10, 2) NOT NULL,
	category VARCHAR(100) NOT NULL,
	stock INT NOT NULL
);    

create table Orders(
	order_id INT PRIMARY KEY AUTO_INCREMENT,
	user_id INT,
	order_date DATE NOT NULL,
	total_amount DECIMAL(10, 2) NOT NULL,
    foreign key(user_id) references Users(user_id)
);   
create table OrderDetails(
	order_details_id INT PRIMARY KEY AUTO_INCREMENT,
	order_id INT,
	product_id INT,
	quantity INT NOT NULL,
    foreign key(order_id) references Orders(order_id),
    foreign key(product_id) references Products(product_id)
);    

INSERT INTO Users (name, email, registered_date, membership) 
VALUES
('Alice Johnson', 'alice.j@example.com', '2024-01-15', 'Prime'),
('Bob Smith', 'bob.s@example.com', '2024-02-01', 'Basic'),
('Charlie Brown', 'charlie.b@example.com', '2024-03-10', 'Prime'),
('Daisy Ridley', 'daisy.r@example.com', '2024-04-12', 'Basic');

INSERT INTO Products (name, price, category, stock) 
VALUES
('Echo Dot', 49.99, 'Electronics', 120),
('Kindle Paperwhite', 129.99, 'Books', 50),
('Fire Stick', 39.99, 'Electronics', 80),
('Yoga Mat', 19.99, 'Fitness', 200),
('Wireless Mouse', 24.99, 'Electronics', 150);

INSERT INTO Orders (user_id, order_date, total_amount) 
VALUES
(1, '2024-05-01', 79.98),
(2, '2024-05-03', 129.99),
(1, '2024-05-04', 49.99),
(3, '2024-05-05', 24.99);

INSERT INTO OrderDetails (order_id, product_id, quantity) 
VALUES
(1, 1, 2),
(2, 2, 1),
(3, 1, 1),
(4, 5, 1);

#1.List all customers who have made purchases of more than $80
select user_id,order_date
from Orders
where total_amount > '80';
SELECT user_id,name
from Users
where user_id='2';
select * from Products
#2.Retrieve all orders placed in the last 280 days along with the customer name and email.
select user_id
from Orders
where order_date> '2024-05.02'; 
#3.Find the average product price for each category.d
select category,avg(price) 
from Products
group by category;
#4.List all customers who have purchased a product from the category Electronics.
select
	Users.Name,
    Products.category
 from
	Users
left join Orders on Users.user_id=Orders.user_id
left join OrderDetails on Orders.order_id=OrderDetails.order_id
left join Products on OrderDetails.product_id=Products.product_id
where Products.category='Electronics';
select * from products
#5.Find the total number of products sold and the total revenue generated for each product.
SELECT 
    Products.name AS product_name, 
    SUM(OrderDetails.quantity) AS total_quantity_sold, 
    SUM(OrderDetails.quantity * Products.price) AS total_revenue
FROM 
    OrderDetails 
JOIN 
    Products  ON OrderDetails.product_id = Products.product_id
GROUP BY 
    Products.product_id;
#6.Update the price of all products in the Books category, increasing it by 10%.
SET SQL_SAFE_UPDATES = 0;

UPDATE                                                                                                      
    Products
SET 
    price = price * 1.10
WHERE 
    category = 'Books';    
#7.Remove all orders that were placed before 2020.    
DELETE FROM Orders
WHERE order_date < '2020-01-01';
#8.Write a query to fetch the order details, including customer name, product name, and 
quantity, for orders placed on 2024-05-01.
select Orders.order_id,Users.Name AS customer_name,Products.name as product_name ,OrderDetails.quantity
 
from Orders
left join Users on Users.user_id=Orders.user_id
left join OrderDetails on Orders.order_id=OrderDetails.order_id
left join Products on OrderDetails.product_id=Products.product_id
where Orders.order_date='2024-05-03';

#9.Fetch all customers and the total number of orders they have placed.
select Users.Name, COUNT(Orders.order_id) AS total_orders
from Users
left join Orders on Users.user_id=Orders.user_id
group by Users.user_id;
10.List all customers who purchased more than 3 units of any produc
t, including the product name and total quantity purchased.
select 
	Users.Name,
    Products.name,
    sum(OrderDetails.quantity) as no_quantity
from Users
left join Orders on Orders.user_id=Users.user_id
left join Orderdetails on OrderDetails.order_id=Orders.Order_id
left join Products on Products.product_id=OrderDetails.product_id
GROUP BY 
    Users.user_id, Products.product_id
HAVING 
    no_quantity > 1;   
    select * from Orders
#11.Find the total revenue generated by each category along with the category name.
SELECT 
    Products.category, 
    SUM(OrderDetails.quantity * Products.price) AS total_revenue
FROM 
    Products 
JOIN 
    OrderDetails  ON Products.product_id = OrderDetails.product_id
GROUP BY 
    Products.category;